
# General server config
server:
#  path: /
#  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
development:
  modules: plugins
  config: config

# Session storage
sessions:
  redis:
    host: redis
    password: password
  prefix: pylon_session_auth_

# Traefik config
traefik:
  redis:
    host: redis
    password: password
  rootkey: traefik
  entrypoint: http
  rule: PathPrefix(`/`)
  node_name: core
  node_hostname: pylon
#  node_url: http://pylon:8080

# Events queue
events:
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512

# Module/config storage
storage:
  endpoint: minio:9000
  access_key: admin
  secret_key: password
  secure: false
  buckets:
    module: module
    config: example

# Settings for Flask application
application:
  SECRET_KEY: "the_earth_is_flat"
#   EXPLAIN_TEMPLATE_LOADING: true

loki:
  buffering: true
  buffer_capacity: 113
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: loki:3100
